# -*- coding: utf-8 -*-
"""Byo_Market_Software_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrSgFYioUtBIeC_V2E8Zzi4WQfADwwGW

##**Descrizione Progetto :**

BioMarket s.a.s ti assume per sviluppare un piccolo software gestionale per la loro nuova bottega in Via Tan 6. Il software deve avere le seguenti funzionalità: Registrare nuovi prodotti, con nome, quantità, prezzo di vendita e prezzo di acquisto.

* Elencare tutti i prodotti presenti.
* Registrare le vendite effettuate.
* Mostrare i profitti lordi e netti.
* Mostrare un menu di aiuto con tutti i comandi disponibili. \
Il software è testuale, quindi utilizzabile da riga di comando.

🔗 Specifiche di Progetto : [Software gestionale per negozio prodotti vegani](https://learn.profession.ai/path-player?courseid=progetto-programmazione-con-python&unit=6628f1d29b29b3bfeb009464Unit)



**************************************************************************
* **Modulo 1 :**  [🐍 Programmazione con Python ](https://learn.profession.aipath-player?courseid=programmazione-con-python&unit=630f72cc69cfc2ed210361ebUnit)
"""

"""
BioMarket Management Software
This program manages a vegan shop warehouse and sales.
Features:
- Add products
- List products
- Sell products
- Show sales
- Calculate profits
- Save and load data from files
"""

import json  # Library to handle JSON file storage

# ----------------------------- Utility Functions -----------------------------

def get_positive_float(prompt):
    """
    Ask the user for a positive float value.
    Keeps asking until the user enters a valid non-negative number.
    """
    while True:
        try:
            value = float(input(prompt))
            if value < 0:
                print("Error: value must be non-negative.")
            else:
                return value
        except ValueError:
            print("Error: please enter a valid number.")


def get_positive_int(prompt):
    """
    Ask the user for a positive integer value.
    Keeps asking until the user enters a valid non-negative integer.
    """
    while True:
        try:
            value = int(input(prompt))
            if value < 0:
                print("Error: value must be non-negative.")
            else:
                return value
        except ValueError:
            print("Error: please enter a valid integer.")

# ----------------------------- Data Persistence -----------------------------

def load_data(filename):
    """
    Load data from a JSON file.
    If the file does not exist, return an empty dictionary.
    """
    try:
        with open(filename, "r") as file:
            return json.load(file)  # Load data as dictionary
    except FileNotFoundError:
        return {}  # If file not found, return empty dict


def save_data(filename, data):
    """
    Save data to a JSON file.
    """
    with open(filename, "w") as file:
        json.dump(data, file, indent=4)  # Save data with indentation

# ----------------------------- Warehouse Functions -----------------------------

def product_add(warehouse):
    """
    Add a new product to the warehouse.
    If the product already exists, update only the quantity.
    """
    name = input("Product name: ")

    if name in warehouse:
        print("Product already exists. Updating quantity...")
        warehouse[name]["quantity"] += get_positive_int("Additional quantity: ")
    else:
        quantity = get_positive_int("Quantity: ")
        purchase_price = get_positive_float("Purchase price: ")
        selling_price = get_positive_float("Selling price: ")

        warehouse[name] = {
            "quantity": quantity,
            "purchase_price": purchase_price,
            "selling_price": selling_price
        }

    print(f"✅ Product '{name}' added/updated successfully!")


def product_list(warehouse):
    """
    List all products in the warehouse with their details.
    """
    if not warehouse:
        print("⚠️ The warehouse is empty.")
    else:
        print("\n📦 Warehouse products:")
        for name, details in warehouse.items():
            print(f"- {name}: Quantity {details['quantity']}, "
                  f"Purchase {details['purchase_price']}€, "
                  f"Selling {details['selling_price']}€")

# ----------------------------- Sales Functions -----------------------------

def product_sell(warehouse, sales):
    """
    Sell a product from the warehouse.
    Decrease quantity and register the sale.
    """
    name = input("Product name to sell: ")

    if name not in warehouse:
        print("⚠️ Product not found in warehouse.")
        return

    if warehouse[name]["quantity"] <= 0:
        print("⚠️ Product out of stock.")
        return

    quantity = get_positive_int("Quantity to sell: ")

    if quantity > warehouse[name]["quantity"]:
        print("⚠️ Not enough stock available.")
        return

    # Update warehouse
    warehouse[name]["quantity"] -= quantity

    # Register sale
    if name in sales:
        sales[name]["quantity"] += quantity
        sales[name]["total_revenue"] += quantity * warehouse[name]["selling_price"]
        sales[name]["total_cost"] += quantity * warehouse[name]["purchase_price"]
    else:
        sales[name] = {
            "quantity": quantity,
            "total_revenue": quantity * warehouse[name]["selling_price"],
            "total_cost": quantity * warehouse[name]["purchase_price"]
        }

    print(f"✅ Sold {quantity} units of '{name}'.")


def sales_list(sales):
    """
    Show all registered sales with details.
    """
    if not sales:
        print("⚠️ No sales registered yet.")
    else:
        print("\n💰 Sales report:")
        for name, details in sales.items():
            print(f"- {name}: Quantity sold {details['quantity']}, "
                  f"Revenue {details['total_revenue']}€, "
                  f"Cost {details['total_cost']}€")

# ----------------------------- Profit Calculation -----------------------------

def calculate_profit(sales):
    """
    Calculate and show the total profit.
    Profit = total revenue - total cost
    """
    total_revenue = sum(item["total_revenue"] for item in sales.values())
    total_cost = sum(item["total_cost"] for item in sales.values())
    profit = total_revenue - total_cost

    print("\n📊 Financial summary:")
    print(f"Total revenue: {total_revenue}€")
    print(f"Total cost: {total_cost}€")
    print(f"Net profit: {profit}€")

# ----------------------------- Main Program -----------------------------

def main():
    """
    Main function that manages the user interface and program execution.
    """
    warehouse = load_data("warehouse.json")  # Load warehouse data
    sales = load_data("sales.json")          # Load sales data

    while True:
        print("\n=== BioMarket Management ===")
        print("Commands available")
        print("add / 1. -> Add product")
        print("list / 2. -> List products")
        print("sell / 3. -> Sell product")
        print("sales / 4. -> Show sales")
        print("profit / 5. -> Calculate profit")
        print("exit / 6. -> Exit")

        choice = input("Choose an option: ").lower().strip()

        if choice in ["1","add"]:
            product_add(warehouse)
        elif choice in ["2","list"]:
            product_list(warehouse)
        elif choice in ["3","sell"]:
            product_sell(warehouse, sales)
        elif choice in ["4","sales"]:
            sales_list(sales)
        elif choice in ["5","profit"]:
            calculate_profit(sales)
        elif choice in ["6","exit"]:
            save_data("warehouse.json", warehouse)
            save_data("sales.json", sales)
            print("💾 Data saved. Exiting program...")
            break
        else:
            print("⚠️ Invalid option, please try again.")

# Run program
if __name__ == "__main__":
    main()