# -*- coding: utf-8 -*-
"""Cross_Selling_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xaigVJAHmGIqhDtm9qU28DQ72tHkrfJr
"""

# ============================================================
#  CROSS-SELLING ASSICURATIVO — MODELLO PREDITTIVO
#  Autore: Francesco Innocenti
#  Obiettivo: Predire l'interesse dei clienti verso una polizza auto
# ============================================================

# ============================
# 1. IMPORT LIBRARIES
# ============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    roc_auc_score,
    roc_curve
)

from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


# ============================
# 2. LOAD DATASET
# ============================

df = pd.read_csv("/content/insurance_cross_sell.csv", index_col=0)

print("DIMENSIONI DATASET")
print(df.shape)
print(df.info())
print(df.describe())


# ============================
# 3. DATA CLEANING & ENCODING
# ============================

df_copy = df.copy().reset_index(drop=True)

gender_mapping = {'Female': 0, 'Male': 1}
age_mapping = {'1-2 Year': 1, '< 1 Year': 2, '> 2 Years': 3}
damage_mapping = {'No': 0, 'Yes': 1}

df_copy['Gender'] = df_copy['Gender'].map(gender_mapping)
df_copy['Vehicle_Age'] = df_copy['Vehicle_Age'].map(age_mapping)
df_copy['Vehicle_Damage'] = df_copy['Vehicle_Damage'].map(damage_mapping)

df_copy['Age'] = pd.to_numeric(df_copy['Age'], errors='coerce')
df_copy['Age'] = df_copy['Age'].fillna(df_copy['Age'].median())

# Drop rows where 'Response' is NaN, as train_test_split does not handle them
df_copy.dropna(subset=['Response'], inplace=True)


# ============================
# 4. CORRELATION ANALYSIS
# ============================

plt.figure(figsize=(14, 10), dpi=100)
sns.heatmap(df_copy.corr(), annot=True, cmap="viridis")
plt.title("Correlation Matrix")
plt.show()


# ============================
# 5. TRAIN/TEST SPLIT
# ============================

X = df_copy.drop("Response", axis=1).values
y = df_copy["Response"].values

X_short = df_copy[["Previously_Insured", "Vehicle_Damage",
                   "Policy_Sales_Channel", "Age"]].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y
)

X_short_train, X_short_test, y_short_train, y_short_test = train_test_split(
    X_short, y, stratify=y
)


# ============================
# 6. STANDARDIZATION
# ============================

ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

X_short_train = ss.fit_transform(X_short_train)
X_short_test = ss.transform(X_short_test)


# ============================
# 7. OVERSAMPLING & UNDERSAMPLING
# ============================

oversample = RandomOverSampler(sampling_strategy='minority')
X_over, y_over = oversample.fit_resample(X_train, y_train)
X_short_over, y_short_over = oversample.fit_resample(X_short_train, y_short_train)

undersample = RandomUnderSampler(sampling_strategy='majority')
X_under, y_under = undersample.fit_resample(X_train, y_train)
X_short_under, y_short_under = undersample.fit_resample(X_short_train, y_short_train)


# ============================
# 8. MODEL EVALUATION FUNCTION
# ============================

def evaluate_model(model, data, labels=('NO', 'YES')):
    X, y = data
    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)[:, 1]

    print("========== CLASSIFICATION REPORT ==========")
    print(classification_report(y, y_pred))

    acc = accuracy_score(y, y_pred)
    auc = roc_auc_score(y, y_proba)

    print(f"Accuracy: {acc:.4f}")
    print(f"AUC: {auc:.4f}")

    cm = confusion_matrix(y, y_pred)
    sns.heatmap(cm, annot=True, fmt='g', cmap='Blues')
    plt.title("Confusion Matrix")
    plt.show()

    fpr, tpr, _ = roc_curve(y, y_proba)
    plt.plot(fpr, tpr, label=f"AUC={auc:.3f}")
    plt.plot([0, 1], [0, 1], linestyle='--')
    plt.title("ROC Curve")
    plt.legend()
    plt.show()


# ============================
# 9. LOGISTIC REGRESSION
# ============================

lr = LogisticRegression(class_weight='balanced')
lr.fit(X_train, y_train)

print("\n=== LOGISTIC REGRESSION — TRAIN ===")
evaluate_model(lr, (X_train, y_train))

print("\n=== LOGISTIC REGRESSION — TEST ===")
evaluate_model(lr, (X_test, y_test))


# ============================
# 10. OVERSAMPLING MODEL
# ============================

lr_over = LogisticRegression(class_weight='balanced')
lr_over.fit(X_over, y_over)

print("\n=== OVERSAMPLING — TRAIN ===")
evaluate_model(lr_over, (X_over, y_over))

print("\n=== OVERSAMPLING — TEST ===")
evaluate_model(lr_over, (X_test, y_test))


# ============================
# 11. UNDERSAMPLING MODEL
# ============================

lr_under = LogisticRegression(class_weight='balanced')
lr_under.fit(X_under, y_under)

print("\n=== UNDERSAMPLING — TRAIN ===")
evaluate_model(lr_under, (X_under, y_under))

print("\n=== UNDERSAMPLING — TEST ===")
evaluate_model(lr_under, (X_test, y_test))


# ============================
# 12. MODEL SELECTION
# ============================

print("\nMODELLO FINALE SELEZIONATO: Logistic Regression (class_weight='balanced')")