# -*- coding: utf-8 -*-
"""Booking_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8I01ezzm1usc1DIoO-hR0k7ALDD5W3F

# Multi-AI agent Travel agency

Implementare un sistema multi-agent che simuli un'agenzia di viaggi.
Il cliente può specificare la meta, il numero di notti, il budget totale, preferenze sulla tipologia di hotel (es. 4 stelle) e infine preferenze sulle attività da fare nella città di destinazione (visite ai musei, escursioni nella natura...).
L'agenzia di viaggi è composta da due operatori: un **HotelExpertAgent**, specializzato nella ricerca e selezione dell'hotel più adatto alle esigenze dell'utente, e un **TravelExperienceAgent**, specializzato nel consigliare all'utente le attività da svolgere durante il suo soggiorno.
Per semplicità le informazioni sugli hotel e quelle sulle escursioni sono contenute in due file separati **Hotel.md** e **Experiences.md**, accessibili rispettivamente dall'HotelExpertAgent e dall'TravelExperienceAgent

Puoi utilizzare un framework a scelta tra LangGraph, CrewAI e AutoGen.

###**IMPORTO VARIABILI AMBIENTE**

**OB:**

- Importi i moduli `getpass` (per input sicuro) e `os` (per gestire variabili d’ambiente).

- Definisci `_set_env` per chiedere all’utente di inserire una variabile d’ambiente (qui OPENAI_API_KEY) solo se non è già impostata.

- `getpass.getpass()` → chiede l’input senza mostrarlo a schermo (utile per API key).

- `os.environ[...]` → legge o imposta variabili d’ambiente.
"""

import getpass
import os

def _set_env(var: str):
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"{var}: ")


_set_env("OPENAI_API_KEY")

import getpass
import os

def _set_env(var: str):
  os.environ[var] = getpass.getpass(f"{var}: ")


_set_env("OPENAI_API_KEY")

"""# **SOLUZIONE:** Implementazione con CrewAI

###**INSTALLO CREW AI E TOOLS**

**OB:** Installi **CrewAI** e il pacchetto opzionale `[tools]` che include strumenti integrati (es. FileReadTool, WebScraper, ecc.).
"""

!pip install crewai crewai[tools]

"""###**IMPORTO CLASSI PRINCIPALI**

**OB:** Importi le classi fondamentali:

- `Agent` → definisce un agente AI con ruolo, obiettivo e strumenti.

- `Task` → definisce un compito da assegnare a un agente.

- `Crew` → gruppo di agenti e compiti da eseguire.
"""

from crewai import Agent, Task, Crew

"""###**CONFIGURARE IL MODELLO DI DEFAULT**

**OB:** Imposti il modello LLM predefinito che CrewAI userà per tutti gli agenti (qui `gpt-4o-mini`).
"""

import os

os.environ["OPENAI_MODEL_NAME"] = 'gpt-4o-mini'

"""## Tools

---
Link alla documentazione ufficiale per:

- FileReadTool → leggere contenuto di file. [FileReadTool_Link](https://docs.crewai.com/tools/FileReadTool/)

- Doc. x Creare custom tools. [Creare_Custom_Tools_Link](https://docs.crewai.com/how-to/Create-Custom-Tools/)

###**IMPORTO E INIZIALIZZO FILEROADTOOL**

**OB:** Importi `FileReadTool` e crei due istanze:

- `hotel_info_read_tool` → legge dati da Hotel.md.

- `experience_info_read_tool` → legge dati da Experiences.md.

In questo modo ogni agente potrà accedere solo al file assegnato.
"""

from crewai_tools import FileReadTool

# Initialize the tool with a specific file path, so the agent can only read the content of the specified file
hotel_info_read_tool = FileReadTool(file_path='Hotel.md')

experience_info_read_tool = FileReadTool(file_path='Experiences.md')

"""###**CREAZIONE TOOL PERSONALIZZATO "CALCULATOR"**

**OB:** Crei un tool custom per eseguire calcoli matematici.

- `@tool("Calculator")` → registra la funzione come tool con nome “Calculator”.

- `eval(operation)` → valuta l’espressione matematica passata come stringa.

- Gestisci eventuali errori di sintassi con `try/except`.
"""

from langchain.tools import tool

@tool("Calculator")
def calculate(operation):
  """Useful to perform any mathematica calculations,
  like sum, minus, mutiplcation, division, etc.
  The input to this tool should be a mathematical
  expression, a couple examples are `200*7` or `5000/2*10`
  """
  try:
      return eval(operation)
  except SyntaxError:
      return "Error: Invalid syntax in mathematical expression"

"""## Creating Agents

###**CREAZIONE AGENTE**

---
Vado a creare 2 tipi di **AGENTS** :

1. Hotel Expert Agent
2. Travel Experience Agent

**OB:**
* Definisci un agente con **ruolo**, **obiettivo**, *backstory* e opzioni.
* `allow_delegation=False` → non può delegare ad altri agenti.
* `verbose=True` → log dettagliati.
* `tools` -> insieme di tools utilizzabili dall'agente
"""

hotel_expert_agent = Agent(
    role="HotelExpertAgent",
    goal="Select the best hotel based on user's requests (city, budget, star rating)",
    backstory="You are John, an expert travel operator "
              "with more than 10 years experience. "
              "You are specialized in analyzing user's requests "
              "and suggesting the best hotel based on their preferences. "
              "Your work is the basis for the TravelExperienceAgent to suggest activities ",
    allow_delegation=False,
    tools=[hotel_info_read_tool],
          verbose=True
)

travel_experience_agent = Agent(
    role="TravelExperienceAgent",
    goal="Select the best experiences and activities based on user's preferences and destination city",
    backstory="You are Cathy, an expert travel operator "
              "with more than 10 years experience. "
              "You are specialized in analyzing user's preferences "
              "and finding experience and activities that the user may enjoy the most. ",
    allow_delegation=False,
    tools=[experience_info_read_tool],
	  verbose=True
)

"""## Creating Tasks

###**CREAZIONE TASK**

---

Vado a creare 2 tipi di **TASKS** :

1. Hotel Expert Agent -> Hotel Expert Agent
2. Travel Experience Agentv -> Travel Experience Agent

**OB:** Definisci un compito con **descrizione**, **output atteso** e **agente assegnato.**
"""

hotel_selection = Task(
    description=(
        "1. Find all the available hotels in {city}. \n"
        "2. Consider the user's preferences: {total_budget} total budget, {nights} nights and {star_rating} stars hotel. \n"
        "3. Select the hotel that matches the user's preferences as far as possible. \n"
    ),
    expected_output="A document with the hotel name, its star rating, the price per night and the total price for the whole stay.",
    agent=hotel_expert_agent,
)

experience_selection = Task(
    description=(
        "1. Find all the available experiences in {city}. \n"
        "2. Read the description of each experience. \n"
        "3. Based on user's preference about experiences, i.e. {experience_preferences} select the most exciting ones for the users. \n"
        "4. Prepare a daily experience plan knowing that the user will spend {nights} nights in {city}. You don't need to select an experience for each day, some days may just include a free tour in the city "
    ),
    expected_output="A plan for each day, including the experience selected for that day, a brief description and the reason why the user may really enjoy it. ",
    agent=travel_experience_agent,
)

"""## Creating the Crew

###**CREAZIONE CREW**

**OB:** Crea un team di agenti in ordine sequenziale
"""

crew = Crew(
    agents=[hotel_expert_agent, travel_experience_agent],
    tasks=[hotel_selection, experience_selection],
    verbose=True
)

"""###**AVVIO ESECUZIONE**

**OB:** Avvio la crew passando input (qui il topic).
"""

result = crew.kickoff(
    inputs={
        "city": "Paris",
        "nights": 3,
        "total_budget": 2000,
        "star_rating": 4,
        "experience_preferences": ["museum", "nature"]
    }
)

"""###**VISUALIZZAZIONE**

**OB:** Mostri l’output in formato markdown.
"""

from IPython.display import Markdown
Markdown(result.raw)

"""# **SOLUZIONE**: Implementazione con AutoGen

###**INSTALLAZIONE LIBRERIE**

**OB:** Installo:
- **pyautogen** :  framework per agenti AI conversazionali
- **python-dotenv** : per variabili d’ambiente
"""

!pip install pyautogen --upgrade

import os

"""###**CONFIGURAZIONE MODELLO**

**OB:** Imposto il modello LLM da usare per tutti gli agenti
"""

llm_config = {
    "config_list": [{"model": "gpt-4o-mini", "api_key": os.environ["OPENAI_API_KEY"]}],
}

"""## Tools

https://microsoft.github.io/autogen/docs/tutorial/tool-use/

###**CREAZIONE TOOL PERSONALIZZATO**

**OB:** Definisco funzioni Python come tool:
1. `calculate` -> Tool per calcoli matematici.
2. `read_hotel_info` -> Tool per leggere info file Hotel.md
3. `travel_experiences_info` -> Tool per leggere info file Experiences.md
"""

from typing import Annotated, Literal

from typing import Annotated, Literal

Operator = Literal["+", "-", "*", "/"]


def calculator(a: int, b: int, operator: Annotated[Operator, "operator"]) -> int:
    if operator == "+":
        return a + b
    elif operator == "-":
        return a - b
    elif operator == "*":
        return a * b
    elif operator == "/":
        return int(a / b)
    else:
        raise ValueError("Invalid operator")


def read_hotel_info(file_path: str = "./Hotel.md") -> int:
    """Read the contents of a file"""
    try:
      with open(file_path, "r") as file:
        return file.read()
    except Exception as e:
      return e

def read_experience_info(file_path: str = "./Experiences.md") -> int:
    """Read the contents of a file"""
    try:
      with open(file_path, "r") as file:
        return file.read()
    except Exception as e:
      return e

#file_path: str = "./Experiences.md") ->> search un file nell directory contenente "./Experiences.md"
#-> int: ->> restituisce un valore int as return

"""## Creating Agents

###**AGENTE CON TOOL**

**OB:** Crei un agente esperto di Hotel

---
**Agente** | Componenti :
1. `name`->  nome Agente
2. `system_message` ->  messaggio di stato dell'Agente
3. `description`-> Descrizione Agente
4. `llm_config` ->  LLM associato
5. `function-map` -> Mappatura delle funzioni tools usabili dall'agente con il loro nome
"""

!pip install autogen

from autogen import ConversableAgent

"""**Hotel Expert Agent**"""

hotel_expert_agent = ConversableAgent(
    name="HotelExpertAgent",
    system_message="You are John, an expert travel operator "
              "with more than 10 years experience. "
              "You are specialized in analyzing user's requests "
              "and suggesting the best hotel based on their preferences. "
              "Your work is the basis for the TravelExperienceAgent to suggest activities. "
              "Select the best hotel based on user's requests (city, budget, star rating), following these steps: "
              "1. Find all the available hotels in {city}. \n"
              "2. Consider the user's preferences: {total_budget} total budget, {nights} nights and {star_rating} stars hotel. \n"
              "3. Select the hotel that matches the user's preferences as far as possible. \n",

    description="HotelExpertAgent. Select the best hotel based on user's requests (city, budget, star rating)",
    llm_config=llm_config,
    function_map={"read_hotel_info": read_hotel_info, "calculator": calculator},
)

"""###**REGISTRAZIONE TOOL**

**OB:** Registra il tool per l’uso da parte del modello.

---

In altre parole , vado ad assegnare il tool (funzione `calculator`) e (`read_hotel_info`) all'agente (`hotel_expert_agent`) mediante registrazione con LLM
"""

# Register the tool signature with the assistant agent.
hotel_expert_agent.register_for_llm(name="calculator", description="A simple calculator")(calculator)
hotel_expert_agent.register_for_llm(name="read_hotel_info", description="A tool to read information about hotels in different cities")(read_hotel_info)

"""###**USO TOOL**

**OB:** L’agente usa il tool per rispondere alla domanda.
"""

inputs={
        "city": "Paris",
        "nights": 3,
        "total_budget": 2000,
        "star_rating": 4,
        "experience_preferences": ["museum", "nature"]
    }

import json
reply = hotel_expert_agent.generate_reply(
    messages=[{"content":json.dumps(inputs), "role": "user"}]
)
print(reply)
#json.dumps(inputs) ->> Converte il dizionario inputs in una stringa JSON, così l’agente può leggerlo come testo

"""**Travel Experience Agent**"""

travel_experience_agent = ConversableAgent(
    name="TravelExperienceAgent",
    system_message="You are Cathy, an expert travel operator "
              "with more than 10 years experience. "
              "You are specialized in analyzing user's preferences "
              "and finding experience and activities that the user may enjoy the most. "
              "Select the best experiences and activities based on user's preferences and destination city. "
              "Follow these steps: "
              "1. Find all the available experiences in {city}. \n"
              "2. Read the description of each experience. \n"
              "3. Based on user's preference about experiences, i.e. {experience_preferences} select the most exciting ones for the users. \n"
              "4. Prepare a daily experience plan knowing that the user will spend {nights} nights in {city}. You don't need to select an experience for each day, some days may just include a free tour in the city "
    ,
    description="TravelExperienceAgent. Select the best experiences and activities based on user's preferences and destination city.",
    llm_config=llm_config,
    function_map={"read_experience_info": read_experience_info},
)

travel_experience_agent.register_for_llm(name="read_experience_info", description="A tool to read information about touristic experiences and activities in different cities")(read_experience_info)

"""**Admin** ( `User_proxy` )"""

user_proxy = ConversableAgent(
    name="User",
    system_message="Provide all details about travel preferences",
    description="User. Provide all details about travel preferences",
    human_input_mode="ALWAYS",
    llm_config=llm_config,
)

"""## Creating the GroupChat

###**CREAZIONE GROUPCHAT**

**OB:** Crei una chat di gruppo e un manager per coordinarla.
"""

from autogen import GroupChat, GroupChatManager

groupchat = GroupChat(
    agents=[user_proxy, hotel_expert_agent, travel_experience_agent],
    messages=[],
    max_round=20,


)
manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config)

"""###**REGOLE DI TRANSIZIONE SPEAKER**

**OB:** Definisci chi può parlare dopo chi (policy di transizione).
"""

groupchat = GroupChat(
    agents=[user_proxy, hotel_expert_agent, travel_experience_agent],
    messages=[],
    max_round=20,
    allowed_or_disallowed_speaker_transitions={
        user_proxy: [hotel_expert_agent],
        hotel_expert_agent: [travel_experience_agent],
    },
    speaker_transitions_type="allowed",
)
manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config)

"""## Init the chat with UserProxy agent"""

inputs={
        "city": "Paris",
        "nights": 3,
        "total_budget": 2000,
        "star_rating": 4,
        "experience_preferences": ["museum", "nature"]
    }

user_proxy.initiate_chat(
    manager, message="I want to organize a trip. Here are my preferences about the trip: " + json.dumps(inputs),
    summary_method="reflection_with_llm",
)

#json.dumps(..) ->> Funzione che trasforma in il dizionario in stringa

"""# SOLUZIONE: Implementazione con LangGraph

###**INSTALLAZIONE LIBRERIE**

**OB:** Install:
- **LangGraph** -> per creare workflow di agenti
- **LangChain** -> per orchestrare LLM e tool
- **langchain_openai** -> per usare modelli OpenAI in LangChain
"""

!pip install langgraph langchain langchain_openai

"""## Tools

###**IMPORTARE MODULI BASE**

**OB:** Importi tipi (`Annotated`, `Literal`, `TypedDict`) e classi per:
- Messaggi (`HumanMessage`, `AIMessage`, ecc.)
- Definizione tool (`@tool`)
- Gestione memoria (`MemorySaver`)
- Costruzione grafo (`StateGraph`, `MessagesState`, `START`, `END`)
- Nodi tool (`ToolNode`).
"""

from typing import Annotated, Literal, TypedDict
#Annoted ->> Aggiungere metadata ai tipi (uso : validazione / documentazione)
#Literal ->> Restringe i valori a un'insime di opzioni fissi
#TypeDict ->> Definisce dizionari con chiavi e tipi ben precisi

from langchain_core.messages import HumanMessage
#HumanMessage ->> rappresenta un messaggio inviato dall’utente. È il formato che il modello riceve come input.
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.checkpoint.memory import MemorySaver
#MemorySaver ->> aggiunge memoria alla pipeline. Crea un checkpoint
from langgraph.graph import END, START, StateGraph, MessagesState
#END / START ->> def. punti di uscita e ingresso
#StateGraph ->> struttura principale per costruire il flusso logico.
#MessageState ->> stato che contiene i messaggi scambiati nella conversazione.
from langgraph.prebuilt import ToolNode
#ToolNode ->> nodo già pronto che incapsula uno strumento, così puoi usarlo facilmente nel grafo.
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, AnyMessage
#BaseMessage ->> classe base per tutti i messaggi.
#HumanMessage ->> messaggio dell’utente.
#AIMessage ->> risposta del modello.
#AnyMessage ->>  tipo generico che può essere uno qualsiasi dei precedenti.

# Define the tools for the agent to use
from langchain.tools import tool

"""###**DEFINIZIONE TOOLS**

**Tool** | Calculator

---


**OB:** Tool per calcoli matematici, utile per stimare costi soggiorno.
"""

@tool("Calculator")
def calculate(operation):
  """Perform any math calculations,
  like sum, minus, mutiplcation, division, etc.
  The input to this tool should be a mathematical
  expression, a couple examples are `200*7` or `5000/2*10`.
  Useful for calculating the total cost of a hotel stay
  and checking if it is within your budget.
  """
  try:
      return eval(operation)
  except SyntaxError:
      return "Error: Invalid syntax in mathematical expression"

"""**Tool** | Read Hotel Info

---


**OB:** Tool per leggere informazioni sugli hotel da file.
"""

@tool("ReadHotelInfo")
def read_hotel_info(file_path: str = "./Hotel.md") -> int:
    """Read all the information about hotels in different cities. Useful to select the most convenient hotel for the user. """
    try:
      with open(file_path, "r") as file:
        return file.read()
    except Exception as e:
      return e

"""**Tool** | Read Experience Info

---


**OB:** Tool per leggere informazioni sulle esperienze.
"""

@tool("ReadExperienceInfo")
def read_experience_info(file_path: str = "./Experiences.md") -> int:
    """Read all the information about experiences and activities available in different cities. Useful to select the most suitable experience for the user. """
    try:
      with open(file_path, "r") as file:
        return file.read()
    except Exception as e:
      return e

"""## Tool nodes

###**CREAZIONE TOOLNODE**

**OB:** Creo nodi del grafo che eseguono rispettivi tool
"""

calculator_node = ToolNode([calculate])
read_hotel_info_node = ToolNode([read_hotel_info])
read_experience_info_node = ToolNode([read_experience_info])

"""## Graph nodes

###**DEFINIZIONE HOTEL EXPERT AGENT**

**OB:** Lista tool disponibili per l'agente hotel <br>
- `bind_tools` → collega i tool al modello LLM.
"""

from langchain.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI

#tools
hotel_expert_agent_tools = [calculate, read_hotel_info]
#llm
hotel_expert_agent_model = ChatOpenAI(model="gpt-4o-mini", temperature=0).bind_tools(hotel_expert_agent_tools)

"""**OB:** Prompt template con istruzioni di ruolo e input utente."""

hotel_expert_agent_prompt = ChatPromptTemplate([
    ("system",
      "You are John, an expert travel operator "
      "with more than 10 years experience. "
      "You are specialized in analyzing user's requests "
      "and suggesting the best hotel based on their preferences. "
      "Your work is the basis for the TravelExperienceAgent to suggest activities. "
      "Select the best hotel based on user's requests (city, budget, star rating), following these steps:  "
      "1. Find all the available hotels in city. \n"
      "2. Consider the user's preferences: total budget, nights and hotel stars. \n"
      "3. Select the hotel that matches the user's preferences as far as possible. \n"
      "When you find the best option provide the final answer "
      "with ONLY a JSON with the following keys: hotel_name, star_rating, price_per_night, number_of_nights, total_price, city, experience_preferences "
      "Here are the user's preferences: "
    ),
    ("human", "{user_input}"),
])
print(hotel_expert_agent_prompt)

"""**OB:** Creo una pipeline (prompt -> modello) eseguibile come nodo LangGrapgh"""

#This is the runnable that can be used in a LangGraph node
hotel_expert_agent_runnable = hotel_expert_agent_prompt | hotel_expert_agent_model
hotel_expert_agent_runnable

"""###**TEST HOTEL EXPERT AGENT**

**OB:** Eseguo il runnable con input utente e stampi la risposta
"""

user_input = "I want to travel to Paris for 3 nights, I have a 2000 euros budget. I prefer to stay in 4 star hotels and I love museums and nature"
response = hotel_expert_agent_runnable.invoke({"user_input": user_input})
print(response)

user_input = "hello"
response = hotel_expert_agent_runnable.invoke({"user_input": user_input})
print(response)

user_input = "hello, I would like to go to Paris"
response = hotel_expert_agent_runnable.invoke({"user_input": user_input})
print(response)

"""###**NODO HOTEL EXPERT AGENT**

**OB:** Definisco un nodo di grafo che esegue il runnable e restituisce la risposta come lista di messaggi.
"""

def hotel_expert_agent_node(state: MessagesState):
    messages = state['messages']
    response = hotel_expert_agent_runnable.invoke(messages)
    # We return a list, because this will get added to the existing list
    return {"messages": [response]}

"""###**DEFINIZIONE TRAVEL EXPERIENCE AGENT**

**OB:** Lista tool per l’agente esperienze e binding al modello.
"""

from langchain.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI

#tools
travel_experience_agent_tools = [read_experience_info]
#llm
travel_experience_agent_model = ChatOpenAI(model="gpt-4o-mini", temperature=0).bind_tools(travel_experience_agent_tools)

"""**OB:** Prompt template per l’agente esperienze."""

travel_experience_agent_prompt = ChatPromptTemplate([
    ("system",
     "You are Cathy, an expert travel operator "
      "with more than 10 years experience. "
      "You are specialized in analyzing user's preferences "
      "and finding experience and activities that the user may enjoy the most. "
      "Select the best experiences and activities based on user's experience preferences, destination city and number of nights, following these steps: "
      "1. Find all the available experiences in the city. \n"
      "2. Read the description of each experience. \n"
      "3. Based on user's preference about experiences select the most exciting ones for the users. \n"
      "4. Prepare a daily experience plan. You don't need to select an experience for each day, some days may just include a free tour in the city "
      "When you are ready to provide the final answer "
      "reply with ONLY a JSON with the following keys: hotel_name, star_rating, price_per_night, total_price and daily_experience_plan. "
      "The daily_experience_plan is a Markdown plan for each day, "
      "including the experience selected for that day, a brief description and the reason why the user may really enjoy it."
    ),
    ("human", "{user_input}"),
])

"""**OB:** Creo una pipeline (prompt -> modello) eseguibile per l'Experience Agent"""

#This is the runnable that can be used in a LangGraph node
travel_experience_agent_runnable = travel_experience_agent_prompt | travel_experience_agent_model

"""###**TEST TRAVEL EXPERIENCE**

**OB:** Simulo input JSON con dati hotel e preferenze esperienze, esegui runnable e stampi risposta.
"""

import json
user_input = json.dumps({
  "hotel_name": "Louvre Luxury Inn",
  "star_rating": "★★★★",
  "price_per_night": 190,
  "number_of_nights": 3,
  "total_price": 570,
  "city": "Paris",
  "experience_preferences": ["museums", "nature"]
})
response = travel_experience_agent_runnable.invoke({"user_input": user_input})
print(response)

"""###**NODO TRAVEL EXPERIENCE AGENT**

**OB:** Nodo di grafo per l’agente esperienze, simile a quello dell’agente hotel.
"""

def travel_experience_agent_node(state: MessagesState):
    messages = state['messages']
    response = travel_experience_agent_runnable.invoke(messages)
    # We return a list, because this will get added to the existing list
    return {"messages": [response]}

"""## Graph Edges

###**FUNZIONE DI ROUTING PER HOTEL EXPERT AGENT**

**OB:** Definisce la logica che decide il prossimo passo dopo che ha parlato l’agente hotel.

- Se l’ultimo messaggio (`last_message`) è un’AIMessage e contiene una chiamata a tool (`tool_calls`), restituisci il nome del tool da eseguire.

- Se non c’è chiamata a tool, passa direttamente all’agente esperienze (`travel_experience_agent`).
"""

# Define the function that determines whether to continue or not
def hotel_agent_should_call_tool(state: MessagesState) -> Literal["Calculator", "ReadHotelInfo", "travel_experience_agent","end"]:
    messages = state['messages']
    last_message = messages[-1]
    # If the LLM makes a tool call, then we route to the "tools" node
    if isinstance(last_message, AIMessage) and last_message.tool_calls:
      tool_name = last_message.tool_calls[0]["name"]
      return tool_name
    # If the last message is a final answer, end the graph
    if isinstance(last_message, AIMessage) and "daily_experience_plan" in last_message.content:
        return "end"
    # Otherwise, we move to the other agent
    return "travel_experience_agent"

"""###**FUNZIONE DI ROUTING PER TRAVEL EXPERT AGENT**

**OB:** Stessa logica, ma per l’agente esperienze.

- Se non deve chiamare un tool, il flusso termina (`end`).
"""

# Define the function that determines whether to continue or not
def travel_expert_should_call_tool(state: MessagesState) -> Literal["ReadExperienceInfo", "end"]:
    messages = state['messages']
    last_message = messages[-1]
    # If the LLM makes a tool call, then we route to the "tools" node
    if isinstance(last_message, AIMessage) and last_message.tool_calls:
      tool_name = last_message.tool_calls[0]["name"]
      return tool_name
    # Otherwise, we end
    return "end"

"""## Build and Compile graph

###**CREAZIONE GRAFO E NODI**

**OB:** Crei il grafo di stato (`StateGraph`) e aggiungi i nodi:

- Agenti (`hotel_expert_agent_node`, `travel_experience_agent_node`)

- Tool (`calculator_node`, `read_hotel_info_node`, `read_experience_info_node`)
"""

# Define a new graph
workflow = StateGraph(MessagesState)

workflow.add_node("hotel_expert_agent_node", hotel_expert_agent_node)
workflow.add_node("travel_experience_agent_node", travel_experience_agent_node)

workflow.add_node("calculator_node", calculator_node)
workflow.add_node("read_hotel_info_node", read_hotel_info_node)

workflow.add_node("read_experience_info_node", read_experience_info_node)

"""###**COLLEGAMENTI INIZIALI E CONDIZIONALI**

**OB:** Il flusso parte sempre dall’agente hotel.
"""

workflow.add_edge(START, "hotel_expert_agent_node")

"""**OB:** Dopo l’agente hotel, in base alla funzione `hotel_agent_should_call_tool`, decidi se:
- Eseguire calcolatrice
- Leggere info hotel
- Passare all’agente esperienze
"""

workflow.add_conditional_edges(
    "hotel_expert_agent_node",
    hotel_agent_should_call_tool,
    {
        "Calculator": "calculator_node",
        "ReadHotelInfo": "read_hotel_info_node",
        "travel_experience_agent": "travel_experience_agent_node",
    },
)

"""**OB:** Dopo l’agente esperienze, in base alla funzione `travel_expert_should_call_tool`, decidi se:
- Leggere info esperienze
- Terminare il flusso
"""

workflow.add_conditional_edges(
    "travel_experience_agent_node",
    travel_expert_should_call_tool,
    {
        "ReadExperienceInfo": "read_experience_info_node",
        "end": END,
    },
)

"""###**COLLEGAMENTI DI RITORNO**

**OB:** Dopo aver eseguito un tool, il flusso torna all’agente che lo ha richiesto.
"""

workflow.add_edge("calculator_node", 'hotel_expert_agent_node')
workflow.add_edge("read_hotel_info_node", 'hotel_expert_agent_node')

workflow.add_edge("read_experience_info_node", 'travel_experience_agent_node')

"""###**COLLEGAMENTI DI RITORNO**

**OB:** Dopo aver eseguito un tool, il flusso torna all’agente che lo ha richiesto.
"""

checkpointer = MemorySaver()
app = workflow.compile(checkpointer=checkpointer)

"""###**VISUALIZZARE GRAFO**

**OB:** Provi a disegnare il grafo in formato immagine.
"""

from IPython.display import Image, display

try:
    display(Image(app.get_graph().draw_mermaid_png()))
except:
    # This requires some extra dependencies and is optional
    pass

"""###**ESECUZIONE DEL FLUSSO**

**OB:** Invochi il grafo passando il messaggio dell’utente.

- `ConsoleCallbackHandler()` → mostra log in console.

---
**A cosa serve**: `app.invoke(...)` avvia la pipeline definita in precedenza (che può includere prompt, modelli, tool, memoria, ecc.), processa il messaggio dell’utente e restituisce lo stato finale (`final_state`), che può contenere la risposta del modello e altri dati di esecuzione.
"""

from langchain.callbacks.tracers import ConsoleCallbackHandler
#ConsoleCallbackHandler ->> intercetta gli eventi generati durante l’esecuzione della pipeline (invocazioni di modelli, chiamate a tool, ecc.) e li stampa in tempo reale sulla console.

# Use the Runnable
user_input = "I want to travel to Paris for 3 nights, I have a 2000 euros budget. I prefer to stay in 4 star hotels and I love museums and nature"
#response = hotel_expert_agent_runnable.invoke({"user_input": user_input})

#user_input ->> Testo incapsulato in oggetto HumanMessage e passato all'app come input iniziale
final_state = app.invoke(
    {"messages": [HumanMessage(content=user_input)]},
    config={"configurable": {"thread_id": 42, "recursion_limit": 150}, 'callbacks': [ConsoleCallbackHandler()]}
)

#app.invoke(..) ->> invoco l'applicazione passando :
#{"messages": [HumanMessage(content=user_input)]} ->> il contesto iniziale, cioè una lista di messaggi in formato LangChain (here as a human message)
#config ->>
##"configurable": {"thread_id": 42} ->> a customizable parameter, here used to uniquely identify the "thread" or conversation (useful for multiple sessions or saving state).
##'callbacks': [ConsoleCallbackHandler()] ->> 'callbacks': [ConsoleCallbackHandler()] → the list of callbacks to activate during execution, in this case to print the steps to the console.

final_state["messages"][-1].content

# Create a dummy Hotel.md file with some sample data
hotel_data = """
Paris:
Hotel Le Bristol Paris, 5 stars, 800 euros/night
Four Seasons Hotel George V, Paris, 5 stars, 1000 euros/night
Hotel Plaza Athénée, 5 stars, 900 euros/night
Le Meurice, 5 stars, 850 euros/night
Shangri-La Paris, 5 stars, 950 euros/night
Hotel Regina Louvre, 5 stars, 700 euros/night
Mandarin Oriental, Paris, 5 stars, 1100 euros/night
The Peninsula Paris, 5 stars, 1200 euros/night
Hôtel Raphael, 5 stars, 650 euros/night
Bulgari Hotel Paris, 5 stars, 1300 euros/night
Saint James Paris, 5 stars, 750 euros/night
Le Royal Monceau - Raffles Paris, 5 stars, 1050 euros/night
Cour des Vosges, 5 stars, 780 euros/night
Le Pavillon de la Reine & Spa, 5 stars, 820 euros/night
Relais Christine, 5 stars, 720 euros/night
Hôtel Splendide Royal Paris, 5 stars, 680 euros/night
La Reserve Paris Hotel and Spa, 5 stars, 1150 euros/night
Hotel Fauchon Paris, 5 stars, 600 euros/night
Hotel Lutetia, 5 stars, 920 euros/night
Brach Paris, 5 stars, 550 euros/night

Madrid:
Hotel Riu Plaza España, 4 stars, 150 euros/night
Hyatt Centric Gran Via Madrid, 4 stars, 180 euros/night
Hotel Regina, 4 stars, 120 euros/night
Vincci Capitol, 4 stars, 160 euros/night
Dear Hotel Madrid, 4 stars, 140 euros/night

Rome:
Rome Cavalieri, A Waldorf Astoria Resort, 5 stars, 400 euros/night
Hotel Eden, 5 stars, 450 euros/night
The St. Regis Rome, 5 stars, 500 euros/night
"""

with open("Hotel.md", "w") as f:
    f.write(hotel_data)

# Create a dummy Experiences.md file with some sample data
experience_data = """
Paris:
Louvre Museum: A must-visit for art lovers, home to the Mona Lisa and thousands of other masterpieces.
Musée d'Orsay: Located in a former railway station, this museum houses a vast collection of Impressionist and Post-Impressionist art.
Eiffel Tower: Iconic landmark offering panoramic views of the city.
Seine River Cruise: A relaxing way to see many of Paris's famous landmarks.
Versailles Palace: Day trip to the opulent palace and gardens of Louis XIV.
Luxembourg Gardens: Beautiful public park perfect for a leisurely stroll or picnic.
Montmartre: Historic neighborhood known for its artistic past and the Sacré-Cœur Basilica.
Notre Dame Cathedral: Historic cathedral (currently under restoration).
Catacombs of Paris: Underground ossuaries holding the remains of millions of Parisians.
Disneyland Paris: A fun day out for families and Disney fans.

Nature experiences near Paris:
Fontainebleau Forest: Offers hiking, climbing, and exploring the historic Fontainebleau Palace.
Parc des Buttes-Chaumont: A hilly urban park with a lake, waterfall, and temple.
Bois de Boulogne: Large public park on the western edge of Paris, with gardens, lakes, and sports facilities.

Madrid:
Prado Museum: Houses one of the world's finest collections of European art.
Reina Sofía Museum: Home to Picasso's Guernica and other modern Spanish art.
Royal Palace of Madrid: The official residence of the Spanish royal family.
Retiro Park: A large and beautiful park with a lake, statues, and the Crystal Palace.
Temple of Debod: An ancient Egyptian temple relocated to Madrid, offering great sunset views.

Nature experiences near Madrid:
Sierra de Guadarrama National Park: Offers hiking, skiing, and beautiful mountain scenery.
Casa de Campo: The largest urban park in Spain, with a lake, zoo and amusement park.

Rome:
Colosseum: Ancient Roman amphitheater.
Roman Forum: Ruins of the ancient Roman government center.
Palatine Hill: Overlooking the Roman Forum, one of the oldest parts of Rome.
Vatican City: Includes St. Peter's Basilica and the Vatican Museums (home to the Sistine Chapel).
Borghese Gallery and Gardens: Houses a significant art collection and beautiful gardens.

Nature experiences near Rome:
Villa Borghese Gardens: Extensive landscape gardens in Rome, with walking paths and a lake.
Appian Way Regional Park: An archaeological and nature park along the ancient Appian Way.
"""

with open("Experiences.md", "w") as f:
    f.write(experience_data)

print("Hotel.md and Experiences.md files created successfully.")

"""##### **Create Data Files**

---
*Solution x solve Issue Pre-Code*

The agents need access to hotel and experience information to fulfill the user's request. The following cell will create two markdown files, `Hotel.md` and `Experiences.md`, containing sample data for the agents to read.
"""

# Create a dummy Hotel.md file with some sample data
hotel_data = """
Paris:
Hotel Le Bristol Paris, 5 stars, 800 euros/night
Four Seasons Hotel George V, Paris, 5 stars, 1000 euros/night
Hotel Plaza Athénée, 5 stars, 900 euros/night
Le Meurice, 5 stars, 850 euros/night
Shangri-La Paris, 5 stars, 950 euros/night
Hotel Regina Louvre, 5 stars, 700 euros/night
Mandarin Oriental, Paris, 5 stars, 1100 euros/night
The Peninsula Paris, 5 stars, 1200 euros/night
Hôtel Raphael, 5 stars, 650 euros/night
Bulgari Hotel Paris, 5 stars, 1300 euros/night
Saint James Paris, 5 stars, 750 euros/night
Le Royal Monceau - Raffles Paris, 5 stars, 1050 euros/night
Cour des Vosges, 5 stars, 780 euros/night
Le Pavillon de la Reine & Spa, 5 stars, 820 euros/night
Relais Christine, 5 stars, 720 euros/night
Hôtel Splendide Royal Paris, 5 stars, 680 euros/night
La Reserve Paris Hotel and Spa, 5 stars, 1150 euros/night
Hotel Fauchon Paris, 5 stars, 600 euros/night
Hotel Lutetia, 5 stars, 920 euros/night
Brach Paris, 5 stars, 550 euros/night

Madrid:
Hotel Riu Plaza España, 4 stars, 150 euros/night
Hyatt Centric Gran Via Madrid, 4 stars, 180 euros/night
Hotel Regina, 4 stars, 120 euros/night
Vincci Capitol, 4 stars, 160 euros/night
Dear Hotel Madrid, 4 stars, 140 euros/night

Rome:
Rome Cavalieri, A Waldorf Astoria Resort, 5 stars, 400 euros/night
Hotel Eden, 5 stars, 450 euros/night
The St. Regis Rome, 5 stars, 500 euros/night
"""

with open("Hotel.md", "w") as f:
    f.write(hotel_data)

# Create a dummy Experiences.md file with some sample data
experience_data = """
Paris:
Louvre Museum: A must-visit for art lovers, home to the Mona Lisa and thousands of other masterpieces.
Musée d'Orsay: Located in a former railway station, this museum houses a vast collection of Impressionist and Post-Impressionist art.
Eiffel Tower: Iconic landmark offering panoramic views of the city.
Seine River Cruise: A relaxing way to see many of Paris's famous landmarks.
Versailles Palace: Day trip to the opulent palace and gardens of Louis XIV.
Luxembourg Gardens: Beautiful public park perfect for a leisurely stroll or picnic.
Montmartre: Historic neighborhood known for its artistic past and the Sacré-Cœur Basilica.
Notre Dame Cathedral: Historic cathedral (currently under restoration).
Catacombs of Paris: Underground ossuaries holding the remains of millions of Parisians.
Disneyland Paris: A fun day out for families and Disney fans.

Nature experiences near Paris:
Fontainebleau Forest: Offers hiking, climbing, and exploring the historic Fontainebleau Palace.
Parc des Buttes-Chaumont: A hilly urban park with a lake, waterfall, and temple.
Bois de Boulogne: Large public park on the western edge of Paris, with gardens, lakes, and sports facilities.

Madrid:
Prado Museum: Houses one of the world's finest collections of European art.
Reina Sofía Museum: Home to Picasso's Guernica and other modern Spanish art.
Royal Palace of Madrid: The official residence of the Spanish royal family.
Retiro Park: A large and beautiful park with a lake, statues, and the Crystal Palace.
Temple of Debod: An ancient Egyptian temple relocated to Madrid, offering great sunset views.

Nature experiences near Madrid:
Sierra de Guadarrama National Park: Offers hiking, skiing, and beautiful mountain scenery.
Casa de Campo: The largest urban park in Spain, with a lake, zoo, and amusement park.

Rome:
Colosseum: Ancient Roman amphitheater.
Roman Forum: Ruins of the ancient Roman government center.
Palatine Hill: Overlooking the Roman Forum, one of the oldest parts of Rome.
Vatican City: Includes St. Peter's Basilica and the Vatican Museums (home to the Sistine Chapel).
Borghese Gallery and Gardens: Houses a significant art collection and beautiful gardens.

Nature experiences near Rome:
Villa Borghese Gardens: Extensive landscape gardens in Rome, with walking paths and a lake.
Appian Way Regional Park: An archaeological and nature park along the ancient Appian Way.
"""

with open("Experiences.md", "w") as f:
    f.write(experience_data)

print("Hotel.md and Experiences.md files created successfully.")

"""###**ESTRAZIONE E PULIZIA OUTPUT**

**OB:** Stampa l’ultimo messaggio (risposta finale).

- Rimuove eventuali delimitatori markdown e carica il testo come JSON.
"""

print(final_state["messages"][-1].content)

# Clean the string by removing the '```json' and triple backticks.
cleaned_str = final_state["messages"][-1].content.replace('```json', '').replace('```', '').strip()

# Load the cleaned string as JSON
data = json.loads(cleaned_str)

"""###**VISUALIZZAZIONE PIANO ESPERIENZE**

**OB:** Stampa e mostra in formato markdown il piano giornaliero delle esperienze.
"""

print(data["daily_experience_plan"])

from IPython.display import Markdown
Markdown(data["daily_experience_plan"])

"""####**CARICAMENTO GITHUB**"""